{
  "autocomplete": [
    {
      "trigger": "!",
      "suggestions": [
        { "string": "afklimit",         "icon": "icon-chat-manager", "role": 3 },
        { "string": "botname",          "icon": "icon-chat-manager", "role": 3 },
        { "string": "clearchat",        "icon": "icon-chat-manager", "role": 3 },
        { "string": "cycle",            "icon": "icon-chat-manager", "role": 3 },
        { "string": "cycletimer",       "icon": "icon-chat-manager", "role": 3 },
        { "string": "historyskiplimit", "icon": "icon-chat-manager", "role": 3 },
        { "string": "language",         "icon": "icon-chat-manager", "role": 3 },
        { "string": "locktimer",        "icon": "icon-chat-manager", "role": 3 },
        { "string": "logout",           "icon": "icon-chat-manager", "role": 3 },
        { "string": "refresh",          "icon": "icon-chat-manager", "role": 3 },
        { "string": "usercmdcd",        "icon": "icon-chat-manager", "role": 3 },
        { "string": "usercommands",     "icon": "icon-chat-manager", "role": 3 },
        { "string": "voteskip",         "icon": "icon-chat-manager", "role": 3 },
  
        { "string": "add",          "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "afkremoval",   "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "autoskip",     "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "bouncer+",     "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "cmddel",       "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "historyskip",  "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "lock",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "lockdown",     "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "maxlength",    "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "move",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "remove",       "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "roulette",     "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "songstats",    "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "swap",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "unlock",       "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "welcome",      "icon": "icon-chat-bouncer", "role": 2 },
  
        { "string": "active",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "afkreset",       "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "afktime",        "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "autodisable",    "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "ban",            "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "blacklist",      "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "blinfo",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "cycleguard",     "icon": "icon-chat-bouncer", "role": 2 },
        // !dclookup @user
        // { "string": "dclookup",       "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "english",        "icon": "icon-chat-bouncer", "role": 2 },
        // !eta @user
        // { "string": "eta",            "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "filter",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "forceskip",      "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "jointime",       "icon": "icon-chat-bouncer", "role": 2 },
        // { "string": "kick",           "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "kill",           "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "lockguard",      "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "lockskip",       "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "motd",           "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "mute",           "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "reload",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "restricteta",    "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "sessionstats",   "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "skip",           "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "skippos",        "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "status",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "timeguard",      "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "togglebl",       "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "togglemotd",     "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "togglevoteskip", "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "unban",          "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "unmute",         "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "voteratio",      "icon": "icon-chat-bouncer", "role": 2 },
        { "string": "whois",          "icon": "icon-chat-bouncer", "role": 2 },
        
        { "string": "link",       "icon": "icon-chat-dj" },
  
        { "string": "8ball",        "icon": "icon-community-users" },
        { "string": "autowoot",     "icon": "icon-community-users" },
        { "string": "source",       "icon": "icon-community-users" },
        { "string": "ba",           "icon": "icon-community-users" },
        { "string": "commands",     "icon": "icon-community-users" },
        { "string": "cookie",       "icon": "icon-community-users" },
        { "string": "dclookup",     "icon": "icon-community-users" },
        { "string": "emoji",        "icon": "icon-community-users" },
        { "string": "eta",          "icon": "icon-community-users" },
        { "string": "fb",           "icon": "icon-community-users" },
        { "string": "ghostbuster",  "icon": "icon-community-users" },
        { "string": "gif",          "icon": "icon-community-users" },
        { "string": "help",         "icon": "icon-community-users" },
        { "string": "join",         "icon": "icon-community-users" },
        { "string": "leave",        "icon": "icon-community-users" },
        { "string": "link",         "icon": "icon-community-users" },
        { "string": "ping",         "icon": "icon-community-users" },
        { "string": "rules",        "icon": "icon-community-users" },
        { "string": "theme",        "icon": "icon-community-users" },
        { "string": "website",      "icon": "icon-community-users" },
        { "string": "youtube",      "icon": "icon-community-users" },
        { "string": "stream",       "icon": "icon-community-users" }
      ]
    }
  ]
}
